
channels:
- conda-forge
- pytorch
dependencies:
- python=3.8.10
- pytorch-gpu=1.11.0
- torchvision=0.12.0
- pip
- pip:
  - azureml-core
  - azureml-defaults
  - azure-keyvault-secrets==4.3.0
  - azure-storage-blob
  - azure-storage-file-share
  - future==0.17.1
  - pillow
  - onnx
  - lpips
  - h5py
  - torchmetrics
  - matplotlib
  - scikit-image
  - tqdm
  - opencv-python
  